### ISSUE TITLE
Visualisation of usage Data

### ISSUE THREAD

**Issue by davidak** [syncthing/usage-reporting#1]
i really like the new usage statistics. with graphs it would be even better!

it would be nice to see how the people are updating the client (version: users, time)

@calmh do you have the data from every day?

and a pie chart for os is obvious. also i would combine os and platform in one table and hide the platform by default.

this is my quick mockup:
![syncthing usage data mockup](https://cloud.githubusercontent.com/assets/91113/3403366/e26e63f8-fd65-11e3-81ed-662ffbe37843.jpg)

what do you think?

some idea how to visualize the upper table?

i can make the frontend if @calmh (or someone else) do the changes to the backend.

i would use flot for nice JS/Canvas graphs.

http://www.flotcharts.org/

**Comment by davidak** [comment]
i close this since the graph of users with version is implemented.

**Comment by swaathi** [comment]
I'd like to customize a few things with the Usage Reporting UI. How do I run this locally? Any help would be appreciated!
