### ISSUE TITLE
Syncthing Usage Report - Data syncing

### ISSUE THREAD

**Issue by jamsheer-thottathil** [syncthing/usage-reporting#14]
I have configured synching usage report locally and I am able to access web UI locally. Now I need to sync my syncing data to usage report database. 1-Is there any way to auto sync syncthing data to usage report database? 2-If no, then How i can fill report table ?

**Comment by AudriusButkevicius** [comment]
There is a URL in the config of syncthing you need to change

**Comment by calmh** [comment]
You’ve asked on the forum, and in the Kastelo help form, and now here. The forum is appropriate venue. Have some patience.

**Comment by jamsheer-thottathil** [comment]
As it is urgency I asked here. sorry.
Thank you, @calmh  and @AudriusButkevicius

**Comment by AudriusButkevicius** [comment]
You will just piss people off and people will stop replying to your requests all together.

**Comment by jamsheer-thottathil** [comment]
hmmmm
