### ISSUE TITLE
Usage Metrics unclear

### ISSUE THREAD

**Issue by fnkr** [syncthing/usage-reporting#4]
Can someone please explain how to read the "usage metrics" table? What do the percentage rates stand for?

![image](https://cloud.githubusercontent.com/assets/616991/13512105/112fbd72-e199-11e5-8ba0-5d0429ead68b.png)
https://data.syncthing.net

**Comment by canton7** [comment]
Percentiles. Imagine a graph of memory usage on the X axis, and number of people with that usage on the Y. The resulting curves will be roughly bell-shaped: lots of people around the mean, and trailing off towards the sides. Draw a vertical line such that the area under the curve and to the left of the line represents 5% of the total area under the line (i.e. 5% of the total number of people). The Y value of the point where that line intersects the curve is the 5% value in the table. Likewise the 50% value indicates the average. Etc.

**Comment by AudriusButkevicius** [comment]
http://en.wikipedia.org/wiki/Percentile
