### ISSUE TITLE
Clarify the Active Users per Day and Version graph

### ISSUE THREAD

**Issue by fschwebel** [syncthing/usage-reporting#5]
From what I understand from the curves, when you say _v0.x_ in the legend it actually means _v0.x and older_ cumulated, since the pattern of beta / release is clearly identifiable. It would be good to clarify it, or best imho to change it to a cumulated graph of each version, that would allow a clearer picture.

**Comment by calmh** [comment]
It is a stacked graph of each version. I'm not sure how to clarify this better?
